version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Change this based on your project requirements

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: pytest

  build-docker:
    docker:
      - image: docker:19.03.12  # Docker image for building
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t hamnaahsann/circleci-invoicer .

  push-docker:
    docker:
      - image: docker:19.03.12
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push hamnaahsann/circleci-invoicer

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - test
      - build-docker:
          requires:
            - test
      - push-docker:
          requires:
            - build-docker
